### ISSUE TITLE
Byte array as handler arguments and hub handler

### ISSUE THREAD

**Issue by AndreasTruetschel** [BlazorExtensions/SignalR#19]
When using byte arrays as client handler arguments or as return type of hub handlers, the signal-r ts-client outputs these as `TypedArray`. When passed back to .Net these have to be deserialized either directly or indirectly, but SimpleJson, seems to have a problem deserializing `TypedArray`s to .Net arrays.

**Comment by galvesribeiro** [comment]
Thanks for report that. 

It is precisely the same problem I’m having with Blazor.Extensions.WebUSB... I’m able to send a `byte[]` from C# to JS but when JS try to send a `Uint8Array` it silently fail without any error.

 Had the same insight as you did, to convert it to an ordinary array but that is very inefficient and slow...

In all cases, in order to unblock us, I’m going to merge it and open an issue on Blazor repo linking both BE packages as a problem.

Thanks!
