### ISSUE TITLE
Missing method exception on Build

### ISSUE THREAD

**Issue by Joebu** [BlazorExtensions/SignalR#36]
dotnet  3.0.100-preview6-012264
BlazorExtensions 0.1.9
im using serverside blazor
Im getting this error on init
`   var connection = _hubConnectionBuilder
                .WithUrl("/hubs/ChatHub",
                opt =>
                {
                    opt.LogLevel = SignalRLogLevel.Trace;
                    opt.Transport = HttpTransportType.WebSockets;
                }).Build();`

`System.MissingMethodException: Method not found: 'Void Microsoft.JSInterop.DotNetObjectRef..ctor(System.Object)'.
   at Blazor.Extensions.HubConnection..ctor(IJSRuntime runtime, HttpConnectionOptions options)
   at Blazor.Extensions.HubConnectionBuilder.Build()`

**Comment by djinnet** [comment]
The reason for that error is because of the current build are using the old version to create `DotNetObjectRef`. 
There is a pull request that has the updated version of making the `DotNetObjectRef`. 
#35 

But if I recall, this extension is for the asp.net core hosted version and not for serverside version. Unless someone already got a working sample of serverside blazor to prove me wrong.
I would suggest using the normal signalR version for serverside blazor.

**Comment by galvesribeiro** [comment]
The preview7 package was published. Please try it out.
