### ISSUE TITLE
Server Hub receives ValueTuple with default values

### ISSUE THREAD

**Issue by MichelArendt** [BlazorExtensions/SignalR#60]
I'm having issues with sending a `ValueTuple `to the server as the parameter arrives at the ServerHub with default values apparently. I am not sure if this is a BlazorExtensions or a SignalR issue and I was unable to find any issues related to `ValueTuple `on either GitHubs... Perhaps posting here will shed some light on this matter.

On the client I'm using the following method:
```
public async Task<UserBaseModel?> LoginUserWithOpenIdAsync((string LoginToken, string Code) uriParameters)
{
            await this.ConnectToAPITask;
            if (this.ConnectToAPITask.IsCompleted)
            {
                        Console.WriteLine("======================");
                        Console.WriteLine(uriParameters.LoginToken);
                        Console.WriteLine("======================");
                        UserBaseModel? user = await this.HubConnection.InvokeAsync<UserBaseModel?>("LoginUserWithOpenIdAsync", uriParameters);

                        if (user != null) { } 
            }

            return null;
}
```

The client prints out to console just fine:
`WASM: 7aQ2/1cZvsvZlIbPK26m9T0EGcqPAtAfzoOQ85EoE2s=`

And on the server I have the following method:
```
public async Task<UserBaseModel?> LoginUserWithOpenIdAsync((string LoginToken, string Code) uriParameters)
        {
            Console.WriteLine("======================");
            Console.WriteLine(uriParameters.GetType().ToString());
            if (uriParameters == default(ValueTuple<string, string>))
            {
                Console.WriteLine("Default values");
            }
            Console.WriteLine(uriParameters.LoginToken);
            Console.WriteLine(uriParameters.Code);
            Console.WriteLine("======================");
            ...
}
```

The server appears to be receiving the default values for the `ValueTuple` with two empty strings:
```
======================                                                                                                  System.ValueTuple`2[System.String,System.String]
Default values


======================
```

If I serialize it to JSON I can bypass the issue, but I'd rather avoid it if possible.

Could this be some sort of limitation on either SignalR or BlazorExtensions? If not, any ideas on what might be wrong?

Sorry for the trouble, thanks in advance!

**Comment by galvesribeiro** [comment]
Hello!

I think it is because when you serialize a `Tuple<string, string>` you get this:

![image](https://user-images.githubusercontent.com/4714040/68051940-523e0b00-fcc7-11e9-92db-07bb6cbc9aee.png)

`System.Text.Json` is used by SignalR as the default json serializer now and it is not very flexible (yet) as Json.Net is. I suggest you to do it with a real struct (if you want a value type), POCO or even pass as 2 different parameters.

If you really want to use the old Json.Net, you can follow [this blog post and look for the Integration with SignalR](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) section which explains how to use the old serializer and your problem will be gone.

Since there is nothing we can do with the package here, I'm going to close the issue but feel free to re-open if you still have problems.

Thanks!

**Comment by MichelArendt** [comment]
I'll do as you suggested and use a POCO. Thanks for the quick reply and explanation! That clarifies a lot!
